/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectInput = IDL.Record({
  'difficulty' : IDL.Nat,
  'name' : IDL.Text,
  'examDate' : IDL.Text,
});
export const ScheduleItem = IDL.Record({
  'subject' : IDL.Text,
  'hours' : IDL.Float64,
  'priority' : IDL.Text,
});

export const idlService = IDL.Service({
  'generateSchedule' : IDL.Func(
      [IDL.Vec(SubjectInput), IDL.Float64],
      [IDL.Vec(ScheduleItem)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectInput = IDL.Record({
    'difficulty' : IDL.Nat,
    'name' : IDL.Text,
    'examDate' : IDL.Text,
  });
  const ScheduleItem = IDL.Record({
    'subject' : IDL.Text,
    'hours' : IDL.Float64,
    'priority' : IDL.Text,
  });
  
  return IDL.Service({
    'generateSchedule' : IDL.Func(
        [IDL.Vec(SubjectInput), IDL.Float64],
        [IDL.Vec(ScheduleItem)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };